[package]

name = "poison"
version = "0.1.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
repository = "https://github.com/reem/rust-poison.git"
description = "Utilities for writing poisoned types."
readme = "README.md"
license = "MIT"

